# A simple workflow to automate updating README.md in the magic repo markgreene74/markgreene74

name: update_readme

on:
  push:
    branches: [ main ]

  # run the workflow every Saturday at 00:10
  workflow_dispatch:
  schedule:
    - cron: '10 0 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      work-dir: ./update_readme

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        working-directory: ${{ env.work-dir }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pipenv
          pipenv install --system --skip-lock
#      - name: Run pytest
#        working-directory: ${{ env.work-dir }}
#        run: |
#          pipenv run python -m pytest
      - name: Update README
        working-directory: ${{ env.work-dir }}
        run: |-
          python fetch_fo76_codes.py
          python update_readme.py
          cat ../README.md
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "README-bot"
          git add -A
          git commit -m "Updated content" || exit 0
          git push
